#!/usr/bin/env bash

docker rm -f trim_bot
docker build -t trim_bot:0 .
docker run -d --name trim_bot --restart=always -v /opt/trimiata_1c_bot/.env:/code/.env -v /mnt/PHOTO_SOURCES:/mnt/PHOTO_SOURCES trim_bot:0
